### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by linkocrn** [gameduell/duellbuildandroid#17]
Hello, I am trying to build a project on android but I keep getting this OSError:
http://i.imgur.com/55QuWGS.png

I did the android setup and building the project on HTML5 works fine.
I also tried running the command line tool with administrator rights but it didn't help.
I didn't install any android emulator though since I'm only needing a .APK file. Does it have anything to do with it?

Thanks :)

**Comment by Khaledgarbaya** [comment]
Hi @AlIako can you run the tool with `-verbose` and provide the output?

**Comment by linkocrn** [comment]
Hi @Khaledgarbaya here is the last part of the output when I run "duell build android -verbose":
http://i.imgur.com/BfnLsV2.png

**Comment by linkocrn** [comment]
Here is the full output, if it helps: http://pastebin.com/F8B03a7T

**Comment by Khaledgarbaya** [comment]
hmm maybe @jcxavier or @catdawg can help here

**Comment by catdawg** [comment]
That seems to be using ant for building, and we have been using gradle for a long time, so you might be using an outdated version. Can you show me which libraries and versions you specified on the duell_project.xml file?

**Comment by linkocrn** [comment]
This is the content of the duell_project.xml file:

```
<?xml version="1.0" encoding="utf-8"?>
<project>

    <app title="OpenGL Tutorial" file="OpenGLTutorial" package="net.twotime.opengltutorial" version="0.0.1" company="2time.net"  />
    <main name="Main" />

    <source path="source" />

    <duelllib name="duellkit" version="5.0.0+" />

    <haxelib name="format" version="3.1.2" />

    <library-config>

        <filesystem>
            <static-assets path="assets" />
        </filesystem>

    </library-config>

</project>
```

**Comment by catdawg** [comment]
The duellkit is on version 7 now. Maybe version 5.0.0 had a problem with windows. Can you change it to version 7.0.0+, run "duell update" and see if it works? You will probably have to rerun "duell setup android"

**Comment by Khaledgarbaya** [comment]
`duell setup android -v 5.0.0+` to make sure that you are running the latest version of the setup

**Comment by linkocrn** [comment]
This worked beautifully. Thank you :)
